server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/atguigu_springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456789

#mybatis:
#  mapperLocations: classpath*:/mapper/*Mapper.xml
#  type-aliases-package:

# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_ID
      insert-strategy: NOT_NULL
      update-strategy: NOT_NULL
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.womi.java.modules.common.handle